### ISSUE TITLE
Makefile for openwrt (LEDE) SDK please, building error: Couldn't find libudns

### ISSUE THREAD

**Issue by hqvv** [shadowsocks/libudns#2]
Hi,
I 'd like to compile the latest shadowsocks-libev( 2.6.3) on LEDE SDK.
libev and libsodium are available on LDED sdk, but not libudns.

Please help on this, how can I port libudns to lede (openwrt) ?

Thanks 
HQ

```
checking for malloc... yes
checking for memset... (cached) yes
checking for socket... yes
checking udns.h usability... no
checking udns.h presence... no
checking for udns.h... no
configure: error: Couldn't find libudns. Try installing libudns-dev or udns-devel.
Makefile:85: recipe for target '/home/hqo/source/build_dir/target-mips_24kc_musl-1.1.16/shadowsocks-libev/openssl/shadowsocks-libev-2017-01-25/.configured_yyyyyyy' failed
```

**Comment by tianlichunhong** [comment]
我遇到了同样的问题，哪位大侠给个详细的解决方法。谢谢！

**Comment by hqvv** [comment]
https://github.com/hqvv/openwrt-udns

**Comment by tianlichunhong** [comment]
能否告知详细操作。是将这个git clone https://github.com/hqvv/openwrt-udns.git到哪个目录下，然后./scripts/feeds install openwrt-udns，是这样吗？还请详细指导一下。

**Comment by tianlichunhong** [comment]
git clone https://github.com/hqvv/openwrt-udns.git package/openwrt-udns
root@localhost:~/ddd# ./scripts/feeds install ./package/openwrt-udns
Collecting package info: done
WARNING: No feed for package './package/openwrt-udns' found, maybe it's already part of the standard packages?
如上面，并没有成功。请大侠指导！

**Comment by wenewzhang** [comment]
git clone https://github.com/hqvv/openwrt-udns.git package/network/utils/openwrt-udns
make package/network/utils/openwrt-udns/compile
make
then it's works on openwrt 15
